// Teleport RDP Web Player — Constants
var TPP = {};

TPP.MAGIC_TPPR = 0x52505054;
TPP.HEADER_VER = 4;
TPP.TPPR_TYPE_RDP = 0x0101;
TPP.TPR_SIZE = 512;
TPP.HEADER_BASIC_OFFSET = 64;

TPP.TYPE_RDP_POINTER = 0x12;
TPP.TYPE_RDP_IMAGE = 0x13;
TPP.TYPE_RDP_KEYFRAME = 0x14;

TPP.RDP_IMG_RAW = 0;
TPP.RDP_IMG_BMP = 1;
TPP.RDP_IMG_ALT = 2;

TPP.PKG_HEADER_SIZE = 12;
TPP.IMAGE_INFO_SIZE = 24;
TPP.KEYFRAME_INFO_SIZE = 12;

TPP.MAX_RETRIES = 3;
TPP.RETRY_DELAY_MS = 1000;
TPP.FETCH_TIMEOUT_MS = 30000;
TPP.TICK_MS = 33;
TPP.SILENCE_THRESHOLD_MS = 1000;
TPP.LE = true;
